"""Load and validate YAML config files using ruamel.yaml + Pydantic."""
from __future__ import annotations

from pathlib import Path

from ruamel.yaml import YAML

from flowbyte.config.models import GlobalConfig, PipelineConfig

_yaml = YAML()
_yaml.preserve_quotes = True


def load_global_config(path: Path | str | None = None) -> GlobalConfig:
    import os
    if path is None:
        path = os.environ.get("FLOWBYTE_CONFIG_PATH", "/etc/flowbyte/config.yml")
    p = Path(path)
    if not p.exists():
        return GlobalConfig()
    raw = _yaml.load(p.read_text())
    return GlobalConfig.model_validate(raw or {})


def load_pipeline_config(path: Path | str) -> PipelineConfig:
    p = Path(path)
    raw = _yaml.load(p.read_text())
    return PipelineConfig.model_validate(raw)


def save_pipeline_config(config: PipelineConfig, path: Path | str) -> None:
    """Round-trip safe write — preserves comments in existing YAML."""
    p = Path(path)
    existing: dict = {}
    if p.exists():
        existing = _yaml.load(p.read_text()) or {}

    data = config.model_dump(mode="json", exclude_none=True)
    existing.update(data)
    with p.open("w") as f:
        _yaml.dump(existing, f)


PIPELINE_TEMPLATE = """\
# Flowbyte pipeline config — generated by `flowbyte init {name}`
# Edit credentials_ref + destination, then run `flowbyte validate {name}`

name: {name}

haravan_credentials_ref: "{name}"   # set via: flowbyte creds set {name} --kind haravan
haravan_shop_domain: "your-shop.myharavan.com"

destination:
  host: "localhost"
  port: 5432
  user: "flowbyte"
  database: "flowbyte_data"
  credentials_ref: "pg_main"        # set via: flowbyte creds set pg_main --kind postgres

# Resources — Phase 1 defaults enabled.
# Override schedule with cron expression (timezone from global config.yml).
resources:
  orders:
    enabled: true
    sync_mode: incremental
    schedule: "0 */2 * * *"
    weekly_full_refresh:
      enabled: true
      cron: "0 3 * * 0"

  customers:
    enabled: true
    sync_mode: incremental
    schedule: "5 */2 * * *"
    weekly_full_refresh:
      enabled: true
      cron: "30 3 * * 0"

  products:
    enabled: true
    sync_mode: incremental
    schedule: "10 */12 * * *"
    weekly_full_refresh:
      enabled: true
      cron: "0 4 * * 0"

  inventory_levels:
    enabled: true
    sync_mode: full_refresh
    schedule: "15 */2 * * *"
    weekly_full_refresh:
      enabled: true
      cron: "30 4 * * 0"

  locations:
    enabled: true
    sync_mode: full_refresh
    schedule: "20 0 * * *"
    weekly_full_refresh:
      enabled: true
      cron: "0 5 * * 0"

"""
