"""Bootstrap: generate master key + config templates on first run."""
from __future__ import annotations

import os
import sys
from pathlib import Path

from flowbyte.config.models import AppSettings
from flowbyte.logging import get_logger
from flowbyte.security.master_key import MasterKey

log = get_logger()

_CONFIG_TEMPLATE = """\
# Flowbyte global configuration
# Generated by `flowbyte bootstrap`

timezone: "Asia/Ho_Chi_Minh"

telegram:
  enabled: false
  bot_token: ""
  chat_id: ""

# Optional: override validation thresholds
# validation:
#   soft_delete_sanity_max_pct: 5.0

# Optional: Prometheus metrics
observability:
  prometheus_enabled: true
  prometheus_port: 9091
  prometheus_bind: "127.0.0.1"
"""


def run_bootstrap(settings: AppSettings | None = None) -> None:
    if settings is None:
        settings = AppSettings()

    key_path = Path(settings.master_key_path)
    config_dir = key_path.parent
    pipelines_dir = Path(settings.pipelines_dir)
    config_path = config_dir / "config.yml"

    # Directories
    config_dir.mkdir(parents=True, exist_ok=True)
    pipelines_dir.mkdir(parents=True, exist_ok=True)
    try:
        os.chmod(config_dir, 0o700)
    except OSError:
        pass

    # Master key
    print("Generating master key...")
    key = MasterKey.generate_and_save(key_path)
    print(f"✓ master.key created at {key_path}")
    print(f"  Fingerprint (SHA-256): {key.fingerprint}")
    print()
    print("⚠️  CRITICAL: Backup master.key NOW.")
    print("   If lost, all encrypted credentials become unrecoverable.")
    print()
    print(f"   Backup command:  sudo cp {key_path} /your/secure/backup/location")
    print(f"   Verify SHA-256:  sha256sum /your/secure/backup/location/master.key")
    print()

    confirmed = input("Type 'BACKED-UP' when backup is done: ").strip()
    if confirmed != "BACKED-UP":
        print("Bootstrap aborted. Run again when ready to backup master key.")
        sys.exit(1)

    # Global config template
    if not config_path.exists():
        config_path.write_text(_CONFIG_TEMPLATE)
        print(f"✓ Created {config_path}")

    print()
    print("Bootstrap complete. Next steps:")
    print(f"  flowbyte creds set <name> --kind haravan")
    print(f"  flowbyte init <pipeline-name>")
    print(f"  flowbyte validate <pipeline-name>")
    print(f"  flowbyte enable <pipeline-name>")
